---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  labels:
    app: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: sponmuth/cartservice
          env:
            - name: ELASTIC_APM_SERVER_URL
              value: "http://localhost:5900"
          ports:
            - containerPort: 8080