name: 'eks'

on:
  pull_request:
   branches:
    - master
  workflow_dispatch:    

jobs:
  eks_deployment:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Maven build
        run: |
          sudo apt update
          mvn clean package spring-boot:repackage
      - name: Docker push
        run: |
          docker tag cartservice:0.0.1-SNAPSHOT sponmuth/cartservice
          docker push sponmuth/cartservice
      - name: EKS deployment
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
           aws eks --region us-east-1 update-kubeconfig --name OpenSourceObservabilityStack
           kubectl apply -f deployment.yml
           kubectl apply -f service.yml             